base_link: 'base_link'
# 双臂抓取参数

# =====================================================
xarm: # group name
  object_name : 'water_bottle'  # 被抓取物体的名字
  object_type : 'CYLINDER'      # 被抓取物体的形状：CYLINDER or BOX
  object_size : [0.22, 0.015]   # 被抓取物体的尺寸：CYLINDER [ height,radius];BOX[length, width , hright ]
 
  gripper_state: 0   # 0代表手爪水平抓取东西。

  #default pickup params
  gripper_joints : ['gripper_1_joint', 'gripper_2_joint']  # 手爪
  pregrasp_posture : [0.65, 0.65]   # 张开手爪时的角度
  grasp_posture : [0.05, 0.05]      # 抓取(闭合）手爪时的角度

  # 注意：目前只支持竖直方向的靠近和撤退!
  pre_grasp_approach : [0, 0.11]  # 第一个数，0代表水平靠近，1代表竖直靠近；第二数代表距离，单位米
  post_grasp_retreat : [1, 0.1]  # 第一个数，0代表水平撤退，1代表竖直撤退；第二数代表距离，单位米

  #default place params
  place_pose : [0.2, -0.4, 0 ]    # 目前放置点坐标也采用service输入，所以此参数无效
  pre_place_approach : [1, 0.08]  # 第一个数，0代表水平靠近，1代表竖直靠近；第二数代表距离，单位米
  post_place_retreat : [1, 0.18]  # 第一个数，0代表水平撤退，1代表竖直撤退；第二数代表距离，单位米
  



  
  
  
  

